//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp_Thesis
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantConstraint
    {
        public int ApplicantConstraintID { get; set; }
        public int ApplicantID { get; set; }
        public int ConstraintID { get; set; }
        public bool ApplicantData { get; set; }
    
        public virtual Applicant Applicant { get; set; }
        public virtual Constraint Constraint { get; set; }
    }
}
