//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp_Thesis
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantReceiver
    {
        public int ApplicantReceiverID { get; set; }
        public int ApplicantID { get; set; }
        public int ReceiverID { get; set; }
        public int ApplicantPreference { get; set; }
        public int ReceiverPoints { get; set; }
    
        public virtual Applicant Applicant { get; set; }
        public virtual Receiver Receiver { get; set; }
    }
}
