//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp_Thesis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Constraint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Constraint()
        {
            this.ApplicantConstraint = new HashSet<ApplicantConstraint>();
            this.ReceiverConstraint = new HashSet<ReceiverConstraint>();
        }
    
        public int ConstraintID { get; set; }
        public int LowerBound { get; set; }
        public int UpperBound { get; set; }
        public string ConstraintName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicantConstraint> ApplicantConstraint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiverConstraint> ReceiverConstraint { get; set; }
    }
}
