//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp_Thesis
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiverConstraint
    {
        public int ReceiverConstraintID { get; set; }
        public int ReceiverID { get; set; }
        public int ConstraintID { get; set; }
        public int LowerBound { get; set; }
        public int UpperBound { get; set; }
    
        public virtual Constraint Constraint { get; set; }
        public virtual Receiver Receiver { get; set; }
    }
}
